### ISSUE TITLE
shuye的脚本最近一直在fetching origin死循环

### ISSUE THREAD

**Issue by SoraKasvgano** [AkaneMurakawa/jd-base#1]
'crond[9]: USER root pid  33 cmd bash /jd/jd.sh jd_health_collect
,fatal: ambiguous argument 'origin/main': unknown revision or path not in the working tree.
,'git <command> [<revision>...] -- [<file>...]'
,========================3. 启动挂机程序========================
,========================2. 检测配置文件========================
,更新scripts成功...
,检测到config配置目录下存在crontab.list，自动导入定时任务...
,成功添加定时任务...
,[PM2] PM2 Successfully daemonized
,[PM2] Logs flushed
,[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
,[PM2] Flushing /root/.pm2/pm2.log
,========================1. 更新源代码========================
,--------------------------------------------------------------
,JS脚本目录：/jd/scripts
,crond[9]: crond (busybox 1.31.1) started, log level 8
,系统时间：2021-07-24 15:04:18
,更新shell...
,warning: redirecting to https://github.com.cnpmjs.org/wuzhi04/jd-base/
,Fetching origin
,HEAD is now at b190bf4 Update config.sh.sample
,更新shell成功...
,更新脚本'

具体表现为5678启动失败，但后台仍在运行 无法从面板更新cookie

**Comment by AkaneMurakawa** [comment]
现在修复了
